<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <!-- Bloque la copie de tous les sous-dossiers de langues superflus -->
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationIcon>icon_app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="resources.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon_app.ico" />
    <Content Include="resources.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
  </ItemGroup>

</Project>
